apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "enable-mtls"
  namespace: "microservices"
spec:
  host: "*.microservices.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL